module.exports = {
  content: ['./index.php', './app/**/*.php', './resources/**/*.{php,vue,js}'],
  theme: {
    extend: {
      colors: {
        htr: {
          'canvas': '#EDE8DD',
          'spruce': '#2C3A26',
          'moss': '#879365',
          'charcoal': '#272323',
          'dawn': '#D7684A',
          'ember': '#4F1F1D',
          'fog': '#ADAFA1',
          'river': '#2D4656',
          'dusk': '#363049',
          'sky': '#A0CEC7',
          'flame': '#EE8936',
          'sandstone': '#E8BE7C',
          'bg': '#F7F7F0',
          'logo': '#F7F7F0'
        }
      },
      height: {
        'logo': '157px',
        'logo-small': '66px',
        'mobile-logo': '55px',
      },
      width: {
        'logo': '104px',
        'logo-small': '46px',
        'menu': '794px',
        'mobile-logo': '37px',
      },
      'maxHeight': {
        'hero': '1140px',
        'mobile-hero': '736px',
        'hero-destination': '602px',
        'mobile-hero-destination': '354px',
        'map': '902px',
        'mobile-map': '591px'
      },
      'minHeight': {
        'hero': '1140px',
        'mobile-hero': '736px',
        'hero-destination': '602px',
        'mobile-hero-destination': '354px',
        'testimonial': '1058px',
        'mobile-testimonial': '742px',
      },
      zIndex: {
        '60': 60,
        '70': 70,
      },
      borderWidth: {
        '1': '1px',
        '5': '5px',
      },
      fontFamily: {
        'bicyclette': 'Bicyclette, sans-serif',
        'poppins': 'Poppins, sans-serif',
        'revert': 'revert'
      },
      fontSize: {
        'sm': '14px',
        'md': '16px',
        'base': '18px',
        'lg': '24px',
        'xl': '24px',
        '2xl': '48px',
        '3xl': '48px',
        '4xl': '67px',
        '5xl': '170px',
        'revert': 'revert',
        'cta': '72px',
        'btn-primary': '24px',
        'btn-action': '28px',
        'mobile-btn': '18px',
        'mobile-cta': '36px',
        'mobile-xl': '18px',
        'mobile-2xl': '36px',
        'mobile-3xl': '24px',
        'mobile-4xl': '36px',
        'mobile-5xl': '72px',
        'destinations-nav': '24px',
        'nav': '48px',
        'mobile-nav': '36px',
        'page-header': '72px',
        'mobile-page-header': '40px',
      },
      lineHeight: {
        '2xl': '3rem',
        '3xl': '3.5rem',
        '4xl': '4rem',
        '5xl': '9rem'
      },
      gridTemplateColumns: {
        'portal': '1fr 2fr',
        'intro': '2fr 1fr',
        'newsletter': '0.5fr 2fr',
      },
      'inset': {
        'edge': '-7px'
      },
    },
  },
  corePlugins: [
    'flexDirection',
    'flexWrap',
    'order',
    'alignItems',
    'alignSelf',
    'justifyContent',
    'gridTemplateColumns',
    'gridColumn',
    'columnSpan',
    'gridStart',
    'gap',
    'display',
    'position',
    'inset',
    'zIndex',
    'width',
    'height',
    'maxWidth',
    'maxHeight',
    'minHeight',
    'margin',
    'padding',
    'fontFamily',
    'fontSize',
    'fontWeight',
    'fontStyle',
    'textColor',
    'textAlign',
    'textDecoration',
    'textTransform',
    'lineHeight',
    'letterSpacing',
    'backgroundColor',
    'backgroundSize',
    'backgroundPosition',
    'backgroundRepeat',
    'borderWidth',
    'borderStyle',
    'borderColor',
    'borderRadius',
    'opacity',
    'transition',
    'transitionProperty',
    'transitionDuration',
    'transitionTimingFunction',
    'transform',
    'translate',
    'rotate',
    'cursor',
    'listStyleType',
    'space',
    'spaceBetween',
    'lastOfType',
    'stroke',
    'strokeWidth',
    'fill',
    'overflow',
    'important',
    'appearance',
    'opacity',
    'transform',
    'rotate',
    'scale',
    'scrollMargin',
    'boxShadow',
    'boxShadowColor',
  ],
};
